"""Generate the race's RViz config from the course.

    race_rviz.py > run/race-chicane.rviz

Five robots need five sets of five displays, all of them differing only in a
namespace and a colour, and the colour is the legend -- at 560 px a GIF has no
room for one, so r3's trail being the same blue as r3's label and r3's scan is
the only thing telling a reader which line is stanley.  That was a hand-kept
300-line YAML with the colours typed five times each, and it was already wrong:
the camera had been moved for the chicane's wider lanes and the comment beside
it still described the straight's.

So it is generated, from reactive_autonomous_nav/race_course.py, which is the
same module the robots are spawned from and the launch file reads the
controller assignment from.  A colour cannot disagree with a trail and a
framing cannot outlive the course it was measured for.
"""
from __future__ import annotations

__author__ = "".join(
    chr(c - 7) for c in (104, 105, 107, 124, 115, 39, 121, 104, 111, 116, 104, 117)
)

import sys

from reactive_autonomous_nav.race_course import (
    COLOUR, CONTROLLER, COURSE, FIELD, LANES, RACE_LENGTH, START_Y, wall_poses)

# Metres of margin each side of the outer lanes: a robot is 0.34 m across and
# its name label is drawn at its own base_link, so 0.7 keeps both inside the
# frame.
EDGE = 0.7

# How much orbit distance a metre of grid width costs.  Measured on the
# chicane, whose 6.8 m of lane spacing plus 2 x 0.7 of margin needed 11 to sit
# inside a 912x624 crop -- at 9 the outer two lanes were cut off at the edges.
# It reproduces the straight: 5.2 m of spacing gives 8.9, and 9 is what the
# straight was recorded at, chosen the same way by eye.
DISTANCE_PER_M = 11.0 / 8.2


def rgb(ns):
    return '%d; %d; %d' % COLOUR[ns]


def header():
    yield f'# The five-robot race on the {COURSE}, field {FIELD}, one view.'
    yield '#'
    yield '# GENERATED by sim/race_rviz.py from'
    yield '# reactive_autonomous_nav/race_course.py.  Edit those, not this.'
    yield '#'
    yield '# Fixed frame is `map`, which in this race is not a served map:'
    yield '# sim/grid_tf.py pins each robot\'s odom origin into it at the pose the'
    yield '# robot was spawned at, so all five trees hang off one root and RViz can'
    yield '# draw the whole grid at once.  That is the whole reason the frame names'
    yield '# carry the namespace.'
    yield '#'
    yield '# One colour per robot, and every display for that robot wears it: its'
    yield '# scan, its plan, the line it actually drove, its footprint and the name'
    yield '# of its controller floating over it.'
    yield '#'
    yield '# Each RobotModel carries a TF Prefix.  The display looks up a transform'
    yield '# per link using the link\'s own name out of the URDF, and'
    yield '# robot_state_publisher publishes those prefixed -- r1/base_link, not'
    yield '# base_link -- so without it the display finds nothing for any link and'
    yield '# draws an empty footprint circle.'
    yield '#'
    yield '# No costmap display.  Five 6x6 m local costmaps on lane centres this'
    yield '# close overlap almost completely, and at any alpha that made the'
    yield '# inflation visible the five coloured paths -- the thing the clip is of'
    yield '# -- disappeared under it.  The costmaps are what the controllers are'
    yield '# steering on either way; the footprints and the paths are what shows'
    yield '# whether it worked.'


def displays():
    yield '    - Class: rviz_default_plugins/Grid'
    yield '      Name: Grid'
    yield '      Enabled: true'
    yield '      Color: 96; 100; 108'
    yield '      Cell Size: 1'
    yield '      Plane Cell Count: 40'
    if wall_poses():
        yield '    # The chicane, published latched by sim/grid_tf.py from the same'
        yield '    # numbers it spawns the walls at, so what the clip shows and what'
        yield '    # the robots drive around cannot come apart.'
        yield '    - Class: rviz_default_plugins/MarkerArray'
        yield '      Name: Chicane'
        yield '      Enabled: true'
        yield '      Topic:'
        yield '        Value: /chicane'
        yield '        Durability Policy: Transient Local'
        yield '        Reliability Policy: Reliable'
    yield '    # The controller names, one per robot, in that robot\'s own base'
    yield '    # frame so the label follows it without anyone publishing its pose.'
    yield '    - Class: rviz_default_plugins/MarkerArray'
    yield '      Name: Labels'
    yield '      Enabled: true'
    yield '      Topic:'
    yield '        Value: /race_labels'
    yield '        Durability Policy: Transient Local'
    yield '        Reliability Policy: Reliable'
    for ns in LANES:
        c = rgb(ns)
        yield f'    # --- {ns}: {CONTROLLER[ns]} ' + '-' * (40 - len(CONTROLLER[ns]))
        yield f'    - Class: rviz_default_plugins/RobotModel'
        yield f'      Name: {ns.upper()}Model'
        yield '      Enabled: true'
        yield '      Description Topic:'
        yield f'        Value: /{ns}/robot_description'
        yield '        Durability Policy: Transient Local'
        yield f'      TF Prefix: {ns}'
        yield '      Alpha: 1'
        yield '    - Class: rviz_default_plugins/LaserScan'
        yield f'      Name: {ns.upper()}Scan'
        yield '      Enabled: true'
        yield '      Topic:'
        yield f'        Value: /{ns}/scan'
        yield '        Reliability Policy: Best Effort'
        yield '      Size (m): 0.04'
        yield f'      Color: {c}'
        yield '      Color Transformer: FlatColor'
        yield '      Style: Points'
        yield '    - Class: rviz_default_plugins/Path'
        yield f'      Name: {ns.upper()}Plan'
        yield '      Enabled: true'
        yield f'      Topic: {{Value: /{ns}/plan, Reliability Policy: Reliable}}'
        yield f'      Color: {c}'
        yield '      Line Width: 0.03'
        yield '      Line Style: Billboards'
        yield '      Alpha: 0.5'
        yield '    # The line it drove, from sim/trail.py rather than from the'
        yield '    # controller: one source for all five, so the trails are'
        yield '    # comparable and a nav2 lane has one at all.'
        yield '    - Class: rviz_default_plugins/Path'
        yield f'      Name: {ns.upper()}Driven'
        yield '      Enabled: true'
        yield f'      Topic: {{Value: /{ns}/trail, Reliability Policy: Reliable}}'
        yield f'      Color: {c}'
        yield '      Line Width: 0.07'
        yield '      Line Style: Billboards'
        yield '    - Class: rviz_default_plugins/Polygon'
        yield f'      Name: {ns.upper()}Footprint'
        yield '      Enabled: true'
        yield (f'      Topic: {{Value: /{ns}/local_costmap/published_footprint, '
               f'Reliability Policy: Reliable}}')
        yield f'      Color: {c}'
        yield '      Alpha: 1'
    yield '    - Class: rviz_default_plugins/TF'
    yield '      Name: TF'
    yield '      Enabled: false'


def view():
    lo, hi = min(LANES.values()), max(LANES.values())
    width = (hi - lo) + 2 * EDGE
    dist = DISTANCE_PER_M * width
    yield '  Views:'
    yield '    Current:'
    yield '      Class: rviz_default_plugins/Orbit'
    yield f'      # Behind the grid, looking up the course.  The robots start on'
    yield f'      # y = {START_Y:g} spanning x in [{lo:g}, {hi:g}] and finish on'
    yield f'      # y = {START_Y + RACE_LENGTH:g}, so the focal point is the middle of'
    yield f'      # the run and the distance is what it takes to hold a {width:.1f} m'
    yield f'      # wide, {RACE_LENGTH:g} m long box inside a 912x624 crop.'
    yield f'      Distance: {dist:.1f}'
    yield '      Pitch: 1.1'
    yield '      Yaw: 4.7124'
    yield (f'      Focal Point: {{X: {(lo + hi) / 2:.1f}, '
           f'Y: {START_Y + RACE_LENGTH / 2:.1f}, Z: 0}}')
    yield '      Name: Current View'
    yield '    Saved: ~'


def main():
    out = list(header())
    out += ['Panels:',
            '  - Class: rviz_common/Displays',
            '    Name: Displays',
            '    Property Tree Widget:',
            '      Expanded: ~',
            '    Width: 300',
            'Visualization Manager:',
            '  Class: ""',
            '  Displays:']
    out += list(displays())
    out += ['  Global Options:',
            '    Background Color: 62; 66; 74',
            '    Fixed Frame: map',
            '    Frame Rate: 6',
            '  Tools:',
            '    - Class: rviz_default_plugins/MoveCamera',
            '  Value: true']
    out += list(view())
    out += ['Window Geometry:',
            '  Hide Left Dock: true',
            '  Hide Right Dock: true',
            '  Displays:',
            '    collapsed: true',
            '  Height: 720',
            '  Width: 1280',
            '  QMainWindow State: ""']
    print('\n'.join(out))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
